### ISSUE TITLE
Create Frontend for Electors to Indicate when They're Done Voting

### ISSUE THREAD

**Issue by tylerharter** [pivot-libre/pivot#103]
I added this state to the DB and added a couple APIs.  The curl commands (without the authentication headers) are like this (you can base the axios calls on these):

curl -X GET http://homestead.test/api/election/<N>/get_ready
curl -X POST http://homestead.test/api/election/<N>/set_ready -d '{"approved_version": 1}'
curl -X POST http://homestead.test/api/election/<N>/set_ready -d '{"approved_version": null}'

All the calls return something like this:

{"is_latest": false, "approved_version": null, "latest_version": 1}

When showing the user the ballot, you can make the get_ready GET call.  The ready box should be checked if "is_latest" is true.  The frontend should also remember the "latest_version" later; you'll need it when the elector tries to mark the votes as approved later.

When the electors checks the ready box, you should make the set_ready POST call, setting "approved_version" to the "latest_version" you got from the earlier get_ready call.

If the elector unchecks the ready box, you should call set_ready with "approved_version" set to null.

If you do a set_version, you might get a response indicating that "is_latest" is false.  Why?  This means the administrator was making changes while the elector was voting, so the version of the ballot the elector is trying to mark ready is already obsolete.  I suggest handling this my notifying the elector, suggesting they refresh the page to see the latest ballot.

**Comment by neckberg** [comment]
Created a barebones UI with a 'Reviewed' checkbox on the Ballot page.

Checking the box will either mark the ballot as reviewed for the current version, or will load the latest version and notify the users that the ballot has been updated and needs to be reviewed again.

Unchecking the box will mark the ballot as unreviewed (ie set the approved_version to null).
