### ISSUE TITLE
Deletion of candidates doesn't appear to work

### ISSUE THREAD

**Issue by lucasdailey** [pivot-libre/pivot#116]
When attempting to delete a candidate no feedback is evident and when naving away and back to the page the candidate is still displayed. A hard vs soft delete issue?

**Comment by tylerharter** [comment]
Maybe this is due to https://github.com/pivot-libre/pivot/issues/117?  Not sure if there are frontend changes necessary too. @neckberg

**Comment by neckberg** [comment]
Lucas, I'll let you test again before we close this, but candidate deletion should be working now. I also updated the UI (just slightly for now) to give a little more feedback on save/delete progress (the save button text changes to say what it's doing).

**Comment by tylerharter** [comment]
Nathan's changes seem to have fixed it for me, so closing this.
