### ISSUE TITLE
EA's Can View Election Results

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/pivot#16]
As an Election Administrator (EA) I can view the results, because I want to understand the final rankings.

**Comment by carlschroedl** [comment]
We are close on this! Next step: call RankedPairsCalculator.calculate within the pivot web app.

**Comment by carlschroedl** [comment]
@tylerharter has finished the REST API portion of this in PR #50

**Comment by tylerharter** [comment]
We changed the policy, so this can be done in the GUI now.
