### ISSUE TITLE
Change README to Reflect Version Requirements

### ISSUE THREAD

**Issue by tylerharter** [pivot-libre/pivot#20]
Upon composer install, I get this:

"doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement"

But the README says this:

"Before you start make sure you're running PHP >= 5.6.4"

Should we update the readme, or did we intend to depend on a different version of that package?

**Comment by carlschroedl** [comment]
Thanks for taking a stab at setting up the web app Tyler! The Readme is wrong and should be updated. It should use PHP 7.1. Good catch!

**Comment by carlschroedl** [comment]
Thanks for the PR! Is it time to close this issue?
