### ISSUE TITLE
Improve printability of results page

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/pivot#204]
As Madison City Council Chief of Staff Kwasi Obeng, I need to be able to print the entirety of the election results page to PDF so that I can email it to myself and preserve it for public record.

Currently the only information included in the printed PDF is the content available on the first screen's worth of the page, even if there are more screens' worth of content that can be scrolled to on the same webpage.

The current workaround is to save a screenshot of the top of the page, scroll to the next screen's worth of information, screenshot that, repeat until no more content is left.

**Comment by carlschroedl** [comment]
This behavior was observed using Firefox 61.0.1 (64-bit) on Windows 10.

**Comment by carlschroedl** [comment]
Not sure if relevant, but Firefox was using this extension:
https://testpilot.firefox.com/experiments/containers

**Comment by carlschroedl** [comment]
And the page was printed with Ctrl+P, Selecting "Microsoft Print to PDF" for the printer name.

**Comment by carlschroedl** [comment]
Duplicate of https://github.com/pivot-libre/pivot/issues/95

**Comment by carlschroedl** [comment]
I'm dusting off the old front end skills, taking a crack at this one :)

**Comment by carlschroedl** [comment]
Print view is broken again in Chrome. It may be related to this pr:
https://github.com/pivot-libre/pivot/pull/232
@neckberg any ideas?

**Comment by tylerharter** [comment]
Based on discussion, we'll have a dedicated route that goes to a text-only version of the results.
