### ISSUE TITLE
Enable Squeaky Wheel Bot

### ISSUE THREAD

**Issue by tylerharter** [pivot-libre/pivot#235]

**Comment by carlschroedl** [comment]
Pull requests #238 and #240 demonstrate that codacy is now running analyses on pull requests.
The codacy dashboard is [here](https://app.codacy.com/project/pivot-libre/pivot/dashboard). Tyler and Nathan have been invited to the Codacy team so they should be able to change settings if the wheel gets too squeaky.

**Comment by carlschroedl** [comment]
@neckberg does this look good? Could you please verify that you are able to access the [Code Patterns page](https://app.codacy.com/app/pivot-libre/pivot/patterns/list) and change stuff on it?

**Comment by carlschroedl** [comment]
Gonna close this. Please let me know if you have trouble changing the Code Patterns so that I can adjust permissions.
